apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutuo-simulator
  labels:
    app: mutuo-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mutuo-simulator
  template:
    metadata:
      labels:
        app: mutuo-simulator
    spec:
      containers:
        - name: mutuo-simulator-container
          image: mutuo-simulator:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80